name: continuous integration

on: [push]

jobs:
  jobs_matrix:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-13, windows-2022]
        build_type: [Debug, Release]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Checkout LFS objects
        run: git lfs pull

      - name: Install Qt 6.5
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.5.*'
          target: 'desktop'

      - name: Create build directory
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure
        working-directory: ${{github.workspace}}/build
        run: cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DBUILD_TESTS=ON ..

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build . --config ${{ matrix.build_type }} --verbose

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest --build-config ${{ matrix.build_type }} --extra-verbose .
