name: img2hack build actions

on: [push]

jobs:
  jobs_matrix:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-13, windows-2022]
        build_type: [Debug, Release]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo and download lfs dependencies
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Checkout LFS objects
        run: git lfs pull

      - name: Installing Qt 6.5
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.*'
          target: 'desktop'

      - name: Configure and Build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} ..
          cmake --build . --config ${{ matrix.build_type }}
          ctest -C ${{ matrix.build_type }} -VV .
