name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push]

jobs:
  example_matrix:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-13]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo and download lfs dependencies
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs pull
      - run: |
          ls -l
          cd core
          ls -l
          cd tests
          ls -l
          cd files
          ls -l
      - name: Installing Qt 6.5
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.*'
          target: 'desktop'
      - name: Configure and Build
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .
          ctest -VV .
